/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppBoardBoardIdRouteImport } from './routes/app.board.$boardId'
import { Route as AppOrgOrgIdIndexRouteImport } from './routes/app.org.$orgId.index'
import { Route as AppOrgOrgIdSettingsRouteImport } from './routes/app.org.$orgId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBoardBoardIdRoute = AppBoardBoardIdRouteImport.update({
  id: '/app/board/$boardId',
  path: '/app/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgOrgIdIndexRoute = AppOrgOrgIdIndexRouteImport.update({
  id: '/app/org/$orgId/',
  path: '/app/org/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgOrgIdSettingsRoute = AppOrgOrgIdSettingsRouteImport.update({
  id: '/app/org/$orgId/settings',
  path: '/app/org/$orgId/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/board/$boardId': typeof AppBoardBoardIdRoute
  '/app/org/$orgId/settings': typeof AppOrgOrgIdSettingsRoute
  '/app/org/$orgId/': typeof AppOrgOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/board/$boardId': typeof AppBoardBoardIdRoute
  '/app/org/$orgId/settings': typeof AppOrgOrgIdSettingsRoute
  '/app/org/$orgId': typeof AppOrgOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/board/$boardId': typeof AppBoardBoardIdRoute
  '/app/org/$orgId/settings': typeof AppOrgOrgIdSettingsRoute
  '/app/org/$orgId/': typeof AppOrgOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/profile'
    | '/app/'
    | '/app/board/$boardId'
    | '/app/org/$orgId/settings'
    | '/app/org/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/profile'
    | '/app'
    | '/app/board/$boardId'
    | '/app/org/$orgId/settings'
    | '/app/org/$orgId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/profile'
    | '/app/'
    | '/app/board/$boardId'
    | '/app/org/$orgId/settings'
    | '/app/org/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBoardBoardIdRoute: typeof AppBoardBoardIdRoute
  AppOrgOrgIdSettingsRoute: typeof AppOrgOrgIdSettingsRoute
  AppOrgOrgIdIndexRoute: typeof AppOrgOrgIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/board/$boardId': {
      id: '/app/board/$boardId'
      path: '/app/board/$boardId'
      fullPath: '/app/board/$boardId'
      preLoaderRoute: typeof AppBoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/org/$orgId/': {
      id: '/app/org/$orgId/'
      path: '/app/org/$orgId'
      fullPath: '/app/org/$orgId/'
      preLoaderRoute: typeof AppOrgOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/org/$orgId/settings': {
      id: '/app/org/$orgId/settings'
      path: '/app/org/$orgId/settings'
      fullPath: '/app/org/$orgId/settings'
      preLoaderRoute: typeof AppOrgOrgIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppBoardBoardIdRoute: AppBoardBoardIdRoute,
  AppOrgOrgIdSettingsRoute: AppOrgOrgIdSettingsRoute,
  AppOrgOrgIdIndexRoute: AppOrgOrgIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
